// pages/admin/dashboard/index.vue
<template>
  <div class="space-y-4">
    <h1 class="text-xl font-semibold">관리자 대시보드</h1>

    <div class="grid gap-3 md:grid-cols-4">
      <div class="rounded-lg border border-slate-800 bg-slate-900/40 p-4">
        <div class="text-xs text-slate-400">오늘 CRM 등록</div>
        <div class="mt-1 text-lg">{{ stats.todayRegisteredCount }}</div>
      </div>
      <div class="rounded-lg border border-slate-800 bg-slate-900/40 p-4">
        <div class="text-xs text-slate-400">근태 관리</div>
        <div class="mt-1 text-lg">
          <NuxtLink to="/admin/attendance" class="text-cyan-400 hover:underline">바로 가기</NuxtLink>
        </div>
      </div>
      <div class="rounded-lg border border-slate-800 bg-slate-900/40 p-4">
        <div class="text-xs text-slate-400">직급 관리</div>
        <div class="mt-1 text-lg">
          <NuxtLink to="/admin/users" class="text-cyan-400 hover:underline">바로 가기</NuxtLink>
        </div>
      </div>
      <div class="rounded-lg border border-slate-800 bg-slate-900/40 p-4">
        <div class="text-xs text-slate-400">미분류 IP 로그인</div>
        <div class="mt-1 text-lg">{{ stats.unknownIpCount }}</div>
      </div>
    </div>

    <div class="rounded-lg border border-slate-800 bg-slate-900/40 p-4">
      <div class="text-sm text-slate-300">운영 기준</div>
      <div class="mt-2 text-sm text-slate-400">
        이 CRM은 유튜브에 업로드하는 시스템이 아니라, 업로드 완료 후 URL을 입력받아 업로드 날짜/시간과 기본 통계를 저장하고 비교하는 통계형 CRM입니다.
      </div>
      <div class="mt-2 text-sm text-slate-400">
        유튜브 계정이 여러 개면 관리자 페이지에서 계정 이름과 API 키를 계속 추가할 수 있습니다.
        <NuxtLink to="/admin/youtube-accounts" class="ml-1 text-cyan-400 hover:underline">유튜브 계정 관리</NuxtLink>
      </div>
    </div>

    <div class="rounded-lg border border-slate-800 bg-slate-900/40 p-4">
      <div class="mb-3 text-sm font-medium text-slate-200">최근 등록 영상</div>
      <div v-if="stats.latest.length === 0" class="text-sm text-slate-500">아직 등록된 영상이 없습니다.</div>
      <div v-else class="space-y-2">
        <div v-for="item in stats.latest" :key="item.id" class="rounded-md border border-slate-800 bg-slate-950/60 p-3">
          <div class="font-medium">{{ item.title || '제목 없음' }}</div>
          <div class="mt-1 text-sm text-slate-400">{{ item.stock_name }} · {{ item.content_type === 'longform' ? '롱폼' : '숏폼' }}</div>
          <div class="mt-1 text-xs text-slate-500">조회수 {{ item.view_count ?? 0 }}</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({ middleware: ['auth', 'admin'] })

const supabase = useSupabase()
const stats = ref({
  todayRegisteredCount: 0,
  unknownIpCount: 0,
  latest: [] as Array<{
    id: string
    title: string | null
    stock_name: string
    content_type: 'longform' | 'shortform'
    published_at: string | null
    view_count: number | null
  }>
})

onMounted(async () => {
  const { data } = await supabase.auth.getSession()
  const token = data.session?.access_token
  if (!token) return
  const res = await $fetch('/api/dashboard/admin', {
    headers: { Authorization: `Bearer ${token}` }
  })
  stats.value = res as any
})
</script>

// app/admin/dashboard/page.tsx
'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { AuthGuard } from '@/components/auth-guard'
import { AppShell } from '@/components/app-shell'
import { createSupabaseBrowserClient } from '@/lib/supabase-browser'

type Stats = {
  todayRegisteredCount: number
  unknownIpCount: number
  latest: Array<{
    id: string
    title: string | null
    stock_name: string
    content_type: 'longform' | 'shortform'
    view_count: number | null
  }>
}

export default function AdminDashboardPage() {
  const [stats, setStats] = useState<Stats>({ todayRegisteredCount: 0, unknownIpCount: 0, latest: [] })

  useEffect(() => {
    const run = async () => {
      const supabase = createSupabaseBrowserClient()
      const {
        data: { session }
      } = await supabase.auth.getSession()
      if (!session?.access_token) return
      const res = await fetch('/api/dashboard/admin', {
        headers: { Authorization: `Bearer ${session.access_token}` }
      })
      if (!res.ok) return
      setStats((await res.json()) as Stats)
    }
    void run()
  }, [])

  return (
    <AuthGuard requireAdmin>
      <AppShell title="관리자 대시보드" subtitle="직급 관리, 근태 관리, 유튜브 계정 관리와 전체 통계를 확인합니다.">
        <div className="grid grid-4">
          <div className="metric-card">
            <div className="card-title">오늘 CRM 등록</div>
            <div className="card-value">{stats.todayRegisteredCount}</div>
          </div>
          <div className="metric-card">
            <div className="card-title">근태 관리</div>
            <div className="card-value"><Link className="link" href="/admin/attendance">바로 가기</Link></div>
          </div>
          <div className="metric-card">
            <div className="card-title">직급 관리</div>
            <div className="card-value"><Link className="link" href="/admin/users">바로 가기</Link></div>
          </div>
          <div className="metric-card">
            <div className="card-title">미분류 IP 로그인</div>
            <div className="card-value">{stats.unknownIpCount}</div>
          </div>
        </div>

        <div className="grid grid-2">
          <div className="panel">
            <div className="panel-header">
              <div>
                <div className="panel-title">유튜브 계정</div>
                <p className="panel-subtitle">관리자 페이지에서 채널별 API 키와 이름을 계속 추가할 수 있습니다.</p>
              </div>
            </div>
            <div style={{ marginTop: 16 }}>
              <Link className="button secondary" href="/admin/youtube-accounts">유튜브 계정 관리</Link>
            </div>
          </div>
          <div className="panel">
            <div className="panel-header">
              <div>
                <div className="panel-title">최근 등록 영상</div>
                <p className="panel-subtitle">전체 팀 기준으로 최신 등록 영상과 통계 반영 상태를 확인합니다.</p>
              </div>
            </div>
            <div className="list" style={{ marginTop: 16 }}>
              {stats.latest.length === 0 ? (
                <div className="empty-state">아직 등록된 영상이 없습니다.</div>
              ) : (
                stats.latest.map((item) => (
                  <div className="list-item" key={item.id}>
                    <div>{item.title || '제목 없음'}</div>
                    <div className="small muted">
                      {item.stock_name} · {item.content_type === 'longform' ? '롱폼' : '숏폼'} · 조회수 {item.view_count ?? 0}
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      </AppShell>
    </AuthGuard>
  )
}
