// pages/login/index.vue
<template>
  <div class="mx-auto max-w-md space-y-4">
    <h1 class="text-2xl font-semibold">로그인</h1>

    <div class="rounded-lg border border-slate-800 bg-slate-900/40 p-4 space-y-3">
      <div class="space-y-1">
        <div class="text-sm text-slate-300">이메일</div>
        <input v-model="email" class="w-full rounded-md bg-slate-950 border border-slate-800 px-3 py-2" />
      </div>

      <div class="space-y-1">
        <div class="text-sm text-slate-300">비밀번호</div>
        <input
          v-model="password"
          type="password"
          class="w-full rounded-md bg-slate-950 border border-slate-800 px-3 py-2"
        />
      </div>

      <button
        class="w-full rounded-md bg-cyan-600 px-3 py-2 font-medium hover:bg-cyan-500 disabled:opacity-50"
        :disabled="loading"
        @click="login"
      >
        로그인
      </button>

      <div v-if="errorMsg" class="text-sm text-red-400">{{ errorMsg }}</div>
      <div class="text-sm text-slate-400">
        계정이 없나요?
        <NuxtLink class="text-cyan-400 hover:underline" to="/signup">회원가입</NuxtLink>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const supabase = useSupabase()
const me = useMeState()

const email = ref('')
const password = ref('')
const loading = ref(false)
const errorMsg = ref('')

async function login() {
  errorMsg.value = ''
  loading.value = true
  try {
    const { data, error } = await supabase.auth.signInWithPassword({
      email: email.value.trim(),
      password: password.value
    })

    if (error || !data.session) {
      errorMsg.value = error?.message || '로그인에 실패했습니다.'
      return
    }

    // 로그인 이벤트 기록 (IP 저장)
    await $fetch('/api/auth/log-login', {
      method: 'POST',
      body: { accessToken: data.session.access_token }
    }).catch(() => {})

    const meInfo = await fetchMe()
    const isAdmin = meInfo?.roleType === 'super_admin' || meInfo?.roleType === 'admin'
    await navigateTo(isAdmin ? '/admin/dashboard' : '/creator/dashboard')
  } finally {
    loading.value = false
  }
}
</script>

// app/login/page.tsx
'use client'

import Link from 'next/link'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createSupabaseBrowserClient } from '@/lib/supabase/browser-client'

export default function LoginPage() {
  const router = useRouter()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  const onSubmit = async () => {
    setError('')
    setLoading(true)

    try {
      let loginEmail = email.trim()
      const loginPassword = password

      if (!loginEmail.includes('@')) {
        const res = await fetch('/api/auth/resolve-login', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ loginId: loginEmail })
        })
        const data = await res.json().catch(() => ({}))
        if (!res.ok) {
          setError(data?.error || '아이디를 찾을 수 없습니다.')
          return
        }
        loginEmail = data.email
      }

      const supabase = createSupabaseBrowserClient()
      const { data, error } = await supabase.auth.signInWithPassword({
        email: loginEmail,
        password: loginPassword
      })

      if (error || !data.session?.access_token) {
        setError(error?.message || '로그인에 실패했습니다.')
        return
      }

      await fetch('/api/auth/log-login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ accessToken: data.session.access_token })
      })

      const meRes = await fetch('/api/auth/me', {
        headers: { Authorization: `Bearer ${data.session.access_token}` }
      })

      if (!meRes.ok) {
        setError('프로필 조회에 실패했습니다.')
        return
      }

      const me = (await meRes.json()) as { roleType: string }
      if (['super_admin', 'admin'].includes(me.roleType)) {
        router.push('/admin/dashboard')
      } else {
        router.push('/creator/dashboard')
      }
    } catch (e: any) {
      setError(e?.message || '로그인 중 오류가 발생했습니다.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="auth-wrap">
      {loading ? (
        <div className="loading-overlay">
          <div className="loading-modal">
            <div className="loading-spinner" />
            <div className="loading-text">로그인 중입니다...</div>
          </div>
        </div>
      ) : null}
      <div className="auth-center">
        <div className="panel form-stack" style={{ width: '100%', maxWidth: 520 }}>
          <h1 className="auth-title">여왕개미미디어 CRM</h1>
          <p className="auth-subtitle">DB통계 CRM</p>
          <div className="field">
            <label className="label">아이디</label>
            <input
              className="input"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') void onSubmit()
              }}
            />
          </div>
          <div className="field">
            <label className="label">비밀번호</label>
            <input
              className="input"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') void onSubmit()
              }}
            />
          </div>
          <button className="button" disabled={loading} onClick={onSubmit}>
            로그인
          </button>
          {error ? <div className="message-error small">{error}</div> : null}
          <div className="small muted">
            계정이 없나요? <Link className="link" href="/signup">회원가입</Link>
          </div>
        </div>
      </div>
    </div>
  )
}
