// pages/creator/videos/index.vue
<template>
  <div class="space-y-6">
    <div>
      <h1 class="text-xl font-semibold">영상 등록</h1>
      <p class="mt-1 text-sm text-slate-400">
        유튜브 업로드가 끝난 뒤 영상 주소를 입력하면, 업로드 날짜/시간과 기본 통계가 자동으로 저장됩니다.
      </p>
    </div>

    <div class="grid gap-6 lg:grid-cols-[420px_1fr]">
      <section class="rounded-lg border border-slate-800 bg-slate-900/40 p-4 space-y-4">
        <div class="space-y-1">
          <div class="text-sm text-slate-300">유튜브 계정 선택</div>
          <select v-model="form.youtubeAccountId" class="w-full rounded-md border border-slate-800 bg-slate-950 px-3 py-2">
            <option disabled value="">유튜브 계정을 선택하세요</option>
            <option v-for="account in youtubeAccounts" :key="account.id" :value="account.id">
              {{ account.account_name }}<span v-if="account.channel_name"> · {{ account.channel_name }}</span>
            </option>
          </select>
        </div>

        <div class="space-y-1">
          <div class="text-sm text-slate-300">유튜브 영상 주소</div>
          <input
            v-model="form.youtubeUrl"
            class="w-full rounded-md border border-slate-800 bg-slate-950 px-3 py-2"
            placeholder="https://www.youtube.com/watch?v=..."
          />
        </div>

        <div class="space-y-1">
          <div class="text-sm text-slate-300">콘텐츠 형식</div>
          <select v-model="form.contentType" class="w-full rounded-md border border-slate-800 bg-slate-950 px-3 py-2">
            <option value="longform">롱폼</option>
            <option value="shortform">숏폼</option>
          </select>
        </div>

        <div class="space-y-1">
          <div class="text-sm text-slate-300">주요 종목명</div>
          <input
            v-model="form.stockName"
            class="w-full rounded-md border border-slate-800 bg-slate-950 px-3 py-2"
            placeholder="예: 삼성전자"
          />
        </div>

        <div class="space-y-1">
          <div class="text-sm text-slate-300">카테고리</div>
          <input
            v-model="form.contentCategory"
            class="w-full rounded-md border border-slate-800 bg-slate-950 px-3 py-2"
            placeholder="예: 종목 브리핑"
          />
        </div>

        <button
          class="w-full rounded-md bg-cyan-600 px-3 py-2 font-medium hover:bg-cyan-500 disabled:opacity-50"
          :disabled="loading"
          @click="submitVideo"
        >
          작성 버튼
        </button>

        <div v-if="errorMsg" class="text-sm text-red-400">{{ errorMsg }}</div>
        <div v-if="successMsg" class="text-sm text-emerald-400">{{ successMsg }}</div>
      </section>

      <section class="rounded-lg border border-slate-800 bg-slate-900/40 p-4">
        <div class="mb-3 flex items-center justify-between">
          <div class="text-sm font-medium text-slate-200">최근 등록 영상</div>
          <button class="text-xs text-cyan-400 hover:underline" @click="loadMyVideos">새로고침</button>
        </div>

        <div v-if="items.length === 0" class="text-sm text-slate-500">아직 등록된 영상이 없습니다.</div>

        <div v-else class="space-y-3">
          <div
            v-for="item in items"
            :key="item.id"
            class="rounded-md border border-slate-800 bg-slate-950/60 p-3"
          >
            <div class="font-medium">{{ item.title || '제목 없음' }}</div>
            <div class="mt-1 text-sm text-slate-400">
              {{ item.stock_name }} · {{ item.content_type === 'longform' ? '롱폼' : '숏폼' }}
            </div>
            <div class="mt-1 text-xs text-slate-500">
              업로드 시각: {{ formatDate(item.published_at) }}
            </div>
            <div class="mt-1 text-xs text-slate-500">
              조회수 {{ item.view_count ?? 0 }} · 좋아요 {{ item.like_count ?? 0 }} · 댓글 {{ item.comment_count ?? 0 }}
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({ middleware: ['auth'] })

type VideoItem = {
  id: string
  title: string | null
  stock_name: string
  content_type: 'longform' | 'shortform'
  published_at: string | null
  view_count: number | null
  like_count: number | null
  comment_count: number | null
}

type YoutubeAccountItem = {
  id: string
  account_name: string
  channel_id: string | null
  channel_name: string | null
}

const supabase = useSupabase()
const loading = ref(false)
const errorMsg = ref('')
const successMsg = ref('')
const items = ref<VideoItem[]>([])
const youtubeAccounts = ref<YoutubeAccountItem[]>([])

const form = reactive({
  youtubeAccountId: '',
  youtubeUrl: '',
  contentType: 'longform' as 'longform' | 'shortform',
  stockName: '',
  contentCategory: ''
})

onMounted(async () => {
  await loadYoutubeAccounts()
  await loadMyVideos()
})

async function getAccessToken() {
  const { data } = await supabase.auth.getSession()
  return data.session?.access_token || ''
}

async function loadMyVideos() {
  const token = await getAccessToken()
  if (!token) return

  const res = await $fetch<{ items: VideoItem[] }>('/api/videos/mine', {
    headers: { Authorization: `Bearer ${token}` }
  })
  items.value = res.items || []
}

async function loadYoutubeAccounts() {
  const token = await getAccessToken()
  if (!token) return
  const res = await $fetch<{ items: YoutubeAccountItem[] }>('/api/youtube-accounts/available', {
    headers: { Authorization: `Bearer ${token}` }
  })
  youtubeAccounts.value = res.items || []
  if (!form.youtubeAccountId && youtubeAccounts.value.length > 0) {
    form.youtubeAccountId = youtubeAccounts.value[0].id
  }
}

async function submitVideo() {
  errorMsg.value = ''
  successMsg.value = ''
  loading.value = true
  try {
    const token = await getAccessToken()
    if (!token) {
      errorMsg.value = '로그인이 필요합니다.'
      return
    }

    await $fetch('/api/videos/create', {
      method: 'POST',
      body: {
        accessToken: token,
        youtubeAccountId: form.youtubeAccountId,
        youtubeUrl: form.youtubeUrl.trim(),
        contentType: form.contentType,
        stockName: form.stockName.trim(),
        contentCategory: form.contentCategory.trim() || null
      }
    })

    successMsg.value = '영상이 CRM에 저장되었습니다. 업로드 날짜와 기본 통계도 자동 반영되었습니다.'
    form.youtubeAccountId = youtubeAccounts.value[0]?.id || ''
    form.youtubeUrl = ''
    form.contentType = 'longform'
    form.stockName = ''
    form.contentCategory = ''
    await loadMyVideos()
  } catch (e: any) {
    errorMsg.value = e?.statusMessage || e?.message || '영상 저장에 실패했습니다.'
  } finally {
    loading.value = false
  }
}

function formatDate(value: string | null) {
  if (!value) return '-'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return '-'
  return date.toLocaleString('ko-KR')
}
</script>

// app/creator/videos/page.tsx
'use client'

import { useEffect, useState } from 'react'
import { AuthGuard } from '@/components/auth-guard'
import { AppShell } from '@/components/app-shell'
import { createSupabaseBrowserClient } from '@/lib/supabase-browser'

type YoutubeAccountItem = {
  id: string
  account_name: string
  channel_id: string | null
  channel_name: string | null
}

type VideoItem = {
  id: string
  title: string | null
  stock_name: string
  content_type: 'longform' | 'shortform'
  published_at: string | null
  view_count: number | null
  like_count: number | null
  comment_count: number | null
}

export default function CreatorVideosPage() {
  const [youtubeAccounts, setYoutubeAccounts] = useState<YoutubeAccountItem[]>([])
  const [items, setItems] = useState<VideoItem[]>([])
  const [youtubeAccountId, setYoutubeAccountId] = useState('')
  const [youtubeUrl, setYoutubeUrl] = useState('')
  const [contentType, setContentType] = useState<'longform' | 'shortform'>('longform')
  const [stockName, setStockName] = useState('')
  const [contentCategory, setContentCategory] = useState('')
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  const getAccessToken = async () => {
    const supabase = createSupabaseBrowserClient()
    const {
      data: { session }
    } = await supabase.auth.getSession()
    return session?.access_token || ''
  }

  const loadYoutubeAccounts = async () => {
    const accessToken = await getAccessToken()
    if (!accessToken) return
    const res = await fetch('/api/youtube-accounts/available', {
      headers: { Authorization: `Bearer ${accessToken}` }
    })
    const data = await res.json()
    if (!res.ok) {
      setError(data?.error || '유튜브 계정 목록 조회 실패')
      return
    }
    setYoutubeAccounts(data.items || [])
    if (!youtubeAccountId && data.items?.[0]?.id) {
      setYoutubeAccountId(data.items[0].id)
    }
  }

  const loadMyVideos = async () => {
    const accessToken = await getAccessToken()
    if (!accessToken) return
    const res = await fetch('/api/videos/mine', {
      headers: { Authorization: `Bearer ${accessToken}` }
    })
    const data = await res.json()
    if (!res.ok) {
      setError(data?.error || '영상 목록 조회 실패')
      return
    }
    setItems(data.items || [])
  }

  useEffect(() => {
    void loadYoutubeAccounts()
    void loadMyVideos()
  }, [])

  const submit = async () => {
    setError('')
    setMessage('')
    setLoading(true)
    try {
      const accessToken = await getAccessToken()
      const res = await fetch('/api/videos/create', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          accessToken,
          youtubeAccountId,
          youtubeUrl,
          contentType,
          stockName,
          contentCategory: contentCategory || null
        })
      })
      const data = await res.json()
      if (!res.ok) {
        setError(data?.error || '영상 저장 실패')
        return
      }

      setMessage('영상이 CRM에 저장되었습니다. 업로드 날짜와 기본 통계도 자동 반영되었습니다.')
      setYoutubeUrl('')
      setContentType('longform')
      setStockName('')
      setContentCategory('')
      await loadMyVideos()
    } finally {
      setLoading(false)
    }
  }

  return (
    <AuthGuard>
      <AppShell title="영상 등록" subtitle="업로드 완료 후 URL과 기본 분류만 입력하면 업로드 시각과 통계가 자동 저장됩니다.">
        <div className="grid grid-2">
          <div className="panel form-stack">
            <div className="field">
              <label className="label">유튜브 계정 선택</label>
              <select className="select" value={youtubeAccountId} onChange={(e) => setYoutubeAccountId(e.target.value)}>
                <option value="">유튜브 계정을 선택하세요</option>
                {youtubeAccounts.map((account) => (
                  <option key={account.id} value={account.id}>
                    {account.account_name}{account.channel_name ? ` · ${account.channel_name}` : ''}
                  </option>
                ))}
              </select>
            </div>
            <div className="field">
              <label className="label">유튜브 영상 주소</label>
              <input className="input" value={youtubeUrl} onChange={(e) => setYoutubeUrl(e.target.value)} />
            </div>
            <div className="field">
              <label className="label">콘텐츠 형식</label>
              <select className="select" value={contentType} onChange={(e) => setContentType(e.target.value as 'longform' | 'shortform')}>
                <option value="longform">롱폼</option>
                <option value="shortform">숏폼</option>
              </select>
            </div>
            <div className="field">
              <label className="label">주요 종목명</label>
              <input className="input" value={stockName} onChange={(e) => setStockName(e.target.value)} />
            </div>
            <div className="field">
              <label className="label">카테고리</label>
              <input className="input" value={contentCategory} onChange={(e) => setContentCategory(e.target.value)} />
            </div>
            <button className="button" disabled={loading} onClick={submit}>작성 버튼</button>
            {message ? <div className="message-success small">{message}</div> : null}
            {error ? <div className="message-error small">{error}</div> : null}
          </div>

          <div className="panel">
            <div className="card-title">최근 등록 영상</div>
            <div className="list" style={{ marginTop: 16 }}>
              {items.length === 0 ? (
                <div className="muted">아직 등록된 영상이 없습니다.</div>
              ) : (
                items.map((item) => (
                  <div className="list-item" key={item.id}>
                    <div>{item.title || '제목 없음'}</div>
                    <div className="small muted">
                      {item.stock_name} · {item.content_type === 'longform' ? '롱폼' : '숏폼'}
                    </div>
                    <div className="small muted">
                      조회수 {item.view_count ?? 0} · 좋아요 {item.like_count ?? 0} · 댓글 {item.comment_count ?? 0}
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      </AppShell>
    </AuthGuard>
  )
}
